Repository dscigdtuw/GrowGreen, pull requests merged in 2020-10, with the labels that each got.

#7 Logo sets for Web App
  README.md
  images/Green Simple Illustrated Leaf Environment Logo (1).png
  images/Green Simple Illustrated Leaf Environment Logo.png
  images/Green Simple Illustrated Leaf Environment Logo.zip
Labels: hacktoberfest-accepted, hacktoberfest2020

#11 Updated themes for UI
  README.md
Labels: enhancement, hacktoberfest-accepted

#9 Updated Readme.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2020

#12 Basic structure added React
  grow-green/.gitignore
  grow-green/README.md
  grow-green/package-lock.json
  grow-green/package.json
  grow-green/public/favicon.ico
  grow-green/public/index.html
  grow-green/public/logo192.png
  grow-green/public/logo512.png
  grow-green/public/manifest.json
  grow-green/public/robots.txt
  grow-green/src/App.css
  grow-green/src/App.js
  grow-green/src/App.test.js
  grow-green/src/index.css
  grow-green/src/index.js
  grow-green/src/logo.svg
  grow-green/src/serviceWorker.js
  grow-green/src/setupTests.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2020
